### ISSUE TITLE
stopwords-hu.json & stopwords-hu.txt corrupted / wrong encoding 

### ISSUE THREAD

**Issue by AndreasLohr** [stopwords-iso/stopwords-hu#1]
For example in the file: stopwords-hu.txt there are wrong signs, that doesnot exist in hungarian language. Maybe the file was saved with wrong encoding?
I think the errors have been imported from the file: /raw/language-resource-stopwords.txt At least there are corrupted letters.

**Comment by genediazjr** [comment]
That is a possibility. Any chance you could submit a PR for the fix?
